name: Daily Instagram Uploader

on:
  schedule:
    - cron: '30 12 * * *'   # Runs daily at 6 PM IST (12:30 UTC)
  workflow_dispatch:        # Manual trigger option (optional)

jobs:
  run-uploader:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run uploader script
      env:
        INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
        INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
      run: |
        python uploader.py

